
services:
# user service
  user-service:
    build: ./user-service
    container_name: user-service
    env_file:
      - ./user-service/.env
    ports:
      - "3000:3000"
    command: npm start
# book service
book-service:
    build: ./book-service
    container_name: book-service
    env_file:
      - ./book-service/.env
    ports:
      - "3001:3001"
    command: npm start