version: "3.9"

services:
  user-service:
    build: ./user-service
    container_name: user-service
    env_file:
      - ./user-service/.env
    ports:
      - "3000:3000"
    command: npm start
    networks:
      - app-network

  book-service:
    build: ./book-service
    container_name: book-service
    env_file:
      - ./book-service/.env
    ports:
      - "3001:3001"
    command: npm start
    networks:
      - app-network

  order-service:
    build: ./order-service
    container_name: order-service
    env_file:
      - ./order-service/.env
    ports:
      - "3002:3002"
    command: npm start
    depends_on:
      - user-service
      - book-service
    networks:
      - app-network
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    env_file:
      - ./api-gateway/.env
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - book-service
      - order-service

networks:
  app-network:
    driver: bridge
